#!/usr/bin/env bash
:<<'BSD2CL'

BSD 2-Clause License

Copyright (c) 2021 Andrew Charles Henry McMillan [https://summerti.me]
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

BSD2CL

# shellcheck disable=SC2034
declare -gra BASHSTD_VERSINFO=( 0 1 0 '' alpha )


array-eq(){ # IN1:ARR, IN2:ARR
	local -n _BASHSTD_AE_A=$1 _BASHSTD_AE_B=$2
	local _BASHSTD_AE_I=${#_BASHSTD_AE_A[@]}
	if [[ $_BASHSTD_AE_I -ne ${#_BASHSTD_AE_B[@]} ]]; then
		return 1
	fi
	while (( _BASHSTD_AE_I-- > 0 )); do
		if [[ "${_BASHSTD_AE_A[_BASHSTD_AE_I]}" != "${_BASHSTD_AE_B[_BASHSTD_AE_I]}" ]]; then
			return 1
		fi
	done
	return 0
}

array-concat(){ # OUTPUT:*ARR, INPUT:ARR, ...
	local -n _BASHSTD_CC_OUTPUT=$1 _BASHSTD_CC_INPUT
	shift
	local _BASHSTD_CC_O=()
	for _BASHSTD_CC_INPUT in "$@"; do
		_BASHSTD_CC_O+=( "${_BASHSTD_CC_INPUT[@]}" )
	done
	# shellcheck disable=SC2034
	_BASHSTD_CC_OUTPUT=( "${_BASHSTD_CC_O[@]}" )
	return 0
}

split-str(){ # OUTPUT:*ARR, DELIMITER:STR, INPUT:STR
	local -n _BASHSTD_SS_OUTPUT=$1
	local _BASHSTD_SS_DELIMITER=$2 _BASHSTD_SS_VALUE=$3
	_BASHSTD_SS_OUTPUT=()
	while [[ $_BASHSTD_SS_VALUE = *"$_BASHSTD_SS_DELIMITER"* ]]; do
		_BASHSTD_SS_OUTPUT+=( "${_BASHSTD_SS_VALUE%%$_BASHSTD_SS_DELIMITER*}" )
		_BASHSTD_SS_VALUE=${_BASHSTD_SS_VALUE#*$_BASHSTD_SS_DELIMITER}
	done
	_BASHSTD_SS_OUTPUT+=( "$_BASHSTD_SS_VALUE" )
	return 0
}
